FROM wordpress:${PHP_VERSION}-fpm

# Install dependencies required for Composer
RUN apt-get update && apt-get install -y \
    unzip \
    && rm -rf /var/lib/apt/lists/*

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Set proper permissions
RUN chown -R www-data:www-data /var/www/html 